name: TACS

on:
  push:
    branches:
        - '*'
  pull_request:
    branches:
        - '*'

jobs:
  build: 
    needs: [hi,build]
    runs-on: ubuntu-latest
    environment: 
      token1_TOKEN: ${{ secrets.token1 }}
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: download Download Action
        uses: actions/download-artifact@v4
        with:
          path: ./artifact/upload

      - name: download Download2 Action
        uses: actions/download-artifact@v4
        with:
          path: aaaa
          name: 

      - name: Build 
        run: |
          nodejs script.js
          env: 
            token3_TOKEN: ${{ secrets.token3 }}

      - name: upload Upload Action
        uses: actions/upload-artifact@v4
        with:
          path: ./artifact/upload

  hi: 
    runs-on: uwu
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2



      - name: upload aaa
        uses: actions/upload-artifact@v4
        with:
          path: aaaa
          name: 

